[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "AstroPhotography"
version = "0.6.2"
description = "Python workflow for processing astrophotographic images from amateur telescopes and/or digital cameras"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "GNU General Public License v3" }
authors = [
  { name = "Dave Strickland", email = "dave.strickland@gmail.com" },
]
keywords = ["AstroPhotography"]

classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Natural Language :: English",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
]

dependencies = []

[project.optional-dependencies]
test = ["pytest>=3"]

[project.urls]
Homepage = "https://github.com/DaveStrickland/AstroPhotography"

[project.scripts]
dksraw = "AstroPhotography.cli:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["AstroPhotography", "AstroPhotography.*"]
