#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#  ap_fix_badpix.py
#
#  Patches an image given a hole mask, replacing values within
#  connected holes with a random deviate based on the statistics
#  of the surrounding good pixels.
#
#  Copyright 2025 Dave Strickland <dave.strickland@gmail.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
#  2025-03-16 dks : Initial skeleton.

import argparse

##import sys
import logging
import AstroPhotography as ap


def command_line_opts(argv):
    """Parse command line arguments.

    :param argv: argument list to parse
    """
    parser = argparse.ArgumentParser(
        prog="ap_fix_holes",
        description=(
            "Patches an image given a hole mask, replacing values"
            " within connected holes with a random deviate based on"
            " the statistics of the surrounding good pixels."
        ),
    )

    # Required
    parser.add_argument(
        "input_image",
        metavar="INPUT_IMAGE.FITS",
        help="Path/name of the input image that has bad pixels to patch.",
    )
    parser.add_argument(
        "hole_mask",
        metavar="HOLE_MASK.FITS",
        help=(
            "Path/name of the master badpixel file."
            " This is an integer image with zero at good pixels, non-zero at"
            " bad pixels, e.g. as generated by the ap_find_badpix.py script."
        ),
    )
    parser.add_argument(
        "fixed_image", metavar="OUTPUT_IMAGE.FITS", help="Path/name of the output patched image."
    )

    # Optional
    p_mingood = 20
    p_ming2b_ratio = 2.0
    parser.add_argument(
        "--mingood",
        default=p_mingood,
        type=int,
        help=(
            "This is the minimum number of good pixels around each hole to use"
            " when determining the statistical properties of the local good"
            " pixels. The background region around each hole will be adjusted"
            " in size to make sure there are at least this many good (not"
            " masked) pixels."
            f" Default: {p_mingood} pixels."
        ),
    )
    parser.add_argument(
        "--tgt_ratio",
        default=p_ming2b_ratio,
        type=float,
        help=(
            "This is target ratio of good pixels to hole (masked) pixels to"
            " aim for when determining the size of the background region around"
            " each hole. Each background region has at minimum this ratio of"
            " good to mask pixels, but can have more."
            f" Default: {p_mingood} pixels."
        ),
    )

    parser.add_argument(
        "-v",
        "--verbose",
        default=False,
        action="store_true",
        help="If specified  table of information on each hole processed will be output to stdout.",
    )

    parser.add_argument(
        "-l", "--loglevel", default="INFO", help="Logging message level. Default: INFO"
    )

    args = parser.parse_args(argv)
    return args


def main(args=None):
    p_args = command_line_opts(args)
    p_inp_img = p_args.input_image
    p_inp_mask = p_args.hole_mask
    p_out_img = p_args.fixed_image

    p_hfillmin = p_args.mingood
    p_hfilltgt = p_args.tgt_ratio
    p_verbose = p_args.verbose
    p_loglevel = p_args.loglevel

    # Create an instance of the object that can fix bad pixels.
    filler = ap.ApFixHoles(p_loglevel)

    # Tell it to fix data from files (rather than numpy arrays).
    filler.fix_files(
        p_inp_img,
        p_inp_mask,
        p_out_img,
        hfillmin=p_hfillmin,
        hfilltgt=p_hfilltgt,
        verbose=p_verbose,
    )

    return 0


if __name__ == "__main__":
    try:
        status = main()
    except:
        logging.getLogger(__name__).critical("Shutting down due to fatal error")
        raise  # print stack trace
    else:
        raise SystemExit(status)
